comet:
  display_size: 20
  im_per_row:
    d: 4
    m: 6
    p: 4
    s: 4
  rows_per_log: 5
  tags: []
data:
  check_samples: false
  files:
    base: /miniscratch/_groups/ccai/data/jsons
    train:
      kitti: /miniscratch/_groups/ccai/data/jsons/train_kitti.json
      r: /miniscratch/_groups/ccai/data/jsons/train_r_full.json
      rf: /miniscratch/_groups/ccai/data/jsons/train_rf.json
      s: /miniscratch/_groups/ccai/data/jsons/train_s_fixedholes.json
    val:
      kitti: /miniscratch/_groups/ccai/data/jsons/val_kitti.json
      r: /miniscratch/_groups/ccai/data/jsons/val_r_full.json
      rf: /miniscratch/_groups/ccai/data/jsons/val_rf_labelbox.json
      s: /miniscratch/_groups/ccai/data/jsons/val_s_fixedholes.json
  loaders:
    batch_size: 4
    num_workers: 4
  max_samples: -1
  normalization: default
  transforms:
  - ignore: val
    name: hflip
    p: 0.5
  - ignore: false
    keep_aspect_ratio: true
    name: resize
    new_size: 640
  - center: val
    height: 600
    ignore: false
    name: crop
    width: 600
  - ignore: val
    name: brightness
  - ignore: val
    name: saturation
  - ignore: val
    name: contrast
  - ignore: false
    name: resize
    new_size:
      d: 160
      default: 640
      s: 160
dis:
  default:
    get_intermediate_features: false
    init_gain: 0.02
    init_type: xavier
    input_nc: 3
    n_layers: 4
    ndf: 64
    norm: instance
    num_D: 1
    use_sigmoid: false
  flip_prob: 0.05
  m:
    architecture: base
    gan_type: WGAN_norm
    get_intermediate_features: false
    init_gain: 0.02
    init_type: xavier
    input_nc: 3
    multi_level: false
    n_layers: 4
    ndf: 64
    norm: instance
    num_D: 1
    use_sigmoid: false
    wgan_clamp_lower: -0.01
    wgan_clamp_upper: 0.01
  opt:
    beta1: 0.5
    lr:
      default: 2.0e-05
    lr_gamma: 0.5
    lr_milestones: 5
    lr_policy: step
    lr_step_size: 15
    optimizer: ExtraAdam
  p:
    get_intermediate_features: true
    init_gain: 0.02
    init_type: xavier
    input_nc: 3
    n_layers: 4
    ndf: 64
    norm: instance
    num_D: 3
    use_local_discriminator: false
    use_sigmoid: false
  s:
    gan_type: WGAN_norm
    get_intermediate_features: false
    init_gain: 0.02
    init_type: xavier
    input_nc: 3
    n_layers: 4
    ndf: 64
    norm: instance
    num_D: 1
    use_sigmoid: false
    wgan_clamp_lower: -0.01
    wgan_clamp_upper: 0.01
  soft_shift: 0.2
domains:
- r
- s
gen:
  d:
    activ: lrelu
    architecture: dada
    classify:
      enable: false
      linspace:
        buckets: 256
        max: 6.95
        min: 0.35
    init_gain: 0.02
    init_type: xavier
    loss: sigm
    n_downsample: 3
    n_res: 1
    n_upsample: 3
    norm: batch
    output_dim: 1
    pad_type: reflect
    proj_dim: 32
    upsample_featuremaps: true
  deeplabv2:
    nblocks:
    - 3
    - 4
    - 23
    - 3
    pretrained_model: /miniscratch/_groups/ccai/data/pretrained_models/deeplabv2/DeepLab_resnet_pretrained_imagenet.pth
    use_pretrained: true
  deeplabv3:
    backbone: resnet
    output_stride: 8
    pretrained_model:
      mobilenet: /miniscratch/_groups/ccai/data/pretrained_models/deeplabv3/deeplabv3_plus_mobilenetv2_segmentron.pth
      resnet: /miniscratch/_groups/ccai/data/pretrained_models/deeplabv3/model_CoinCheungDeepLab-v3-plus.pth
    use_pretrained: true
  default:
    activ: lrelu
    init_gain: 0.02
    init_type: xavier
    n_downsample: 3
    n_res: 1
    n_upsample: 3
    norm: spectral
    pad_type: reflect
    proj_dim: 32
  encoder:
    activ: lrelu
    architecture: deeplabv3
    dim: 32
    init_gain: 0.02
    init_type: xavier
    input_dim: 3
    n_downsample: 3
    n_res: 0
    n_upsample: 3
    norm: spectral
    pad_type: reflect
    proj_dim: 32
  m:
    activ: lrelu
    init_gain: 0.02
    init_type: xavier
    n_downsample: 3
    n_res: 3
    n_upsample: 3
    norm: spectral
    output_dim: 1
    pad_type: reflect
    proj_dim: 64
    spade:
      activations:
        all_lrelu: true
      cond_nc: 15
      detach: false
      latent_dim: 128
      num_layers: 3
      spade_param_free_norm: batch
      spade_use_spectral_norm: true
    use_advent: true
    use_ground_intersection: true
    use_low_level_feats: true
    use_minent: true
    use_minent_var: true
    use_pl4m: false
    use_proj: true
    use_spade: true
  opt:
    beta1: 0.9
    lr:
      default: 5.0e-05
    lr_gamma: 0.5
    lr_milestones: 15
    lr_policy: step
    lr_step_size: 5
    optimizer: ExtraAdam
  p:
    activ: lrelu
    diff_aug:
      cutout_ratio: 0.5
      do_color_jittering: false
      do_cutout: false
      do_translation: false
      translation_ratio: 0.125
      use: false
    init_gain: 0.02
    init_type: xavier
    latent_dim: 640
    loss: gan
    n_downsample: 3
    n_res: 1
    n_upsample: 3
    no_z: true
    norm: spectral
    output_dim: 3
    pad_type: reflect
    paste_original_content: true
    pl4m_epoch: 49
    proj_dim: 32
    spade_kernel_size: 3
    spade_n_up: 7
    spade_param_free_norm: instance
    spade_use_spectral_norm: true
    use_final_shortcut: false
  s:
    activ: lrelu
    architecture: deeplabv3
    depth_dada_fusion: true
    depth_feat_fusion: true
    init_gain: 0.02
    init_type: xavier
    n_downsample: 3
    n_res: 1
    n_upsample: 3
    norm: spectral
    num_classes: 11
    output_dim: 11
    pad_type: reflect
    proj_dim: 32
    upsample_featuremaps: false
    use_advent: true
    use_minent: true
load_paths:
  m: config/model/masker/checkpoints/latest_ckpt.pth # relative to $PWD, *not* this file 
  p: none
  pm: none
output_path: /miniscratch/_groups/ccai/experiments/runs/ablation-v0/out--49167587
tasks:
- m
- s
- d
train:
  amp: false
  auto_resume: true
  epochs: 50
  fid:
    batch_size: 50
    dims: 2048
    n_images: 57
  kitti:
    batch_size: 6
    epochs: 10
    pretrain: false
  lambdas:
    C: 1
    G:
      classifier: 1
      d:
        gml: 0.5
        main: 1
      m:
        bce: 1
        gi: 0.05
        pl4m: 1
        tv: 1
      p:
        context: 0
        dm: 1
        featmatch: 10
        gan: 1
        reconstruction: 0
        tv: 0
        vgg: 10
      s:
        advent: 0.001
        crossent: 1
        crossent_pseudo: 0.001
        minent: 0.001
    advent:
      WGAN_gp: 10
      adv_aux: 0.0
      adv_main: 1.0
      dis_aux: 0.0
      dis_main: 1.0
      ent_aux: 0.0
      ent_main: 0.5
      ent_var: 0.1
  latent_domain_adaptation: false
  log_level: 2
  min_save_epoch: 28
  pseudo:
    epochs: 10
    tasks:
    - m
    - s
    - d
  resume: false
  save_n_epochs: 25
val:
  store_images: false
  val_painter: config/model/painter/checkpoints/latest_ckpt.pth # relative to $PWD, *not* this file 
